import './globals.css'
import React from "react";
import {NextFont} from "next/dist/compiled/@next/font";
import {Metadata} from "next";
import {Inter} from 'next/font/google'
import Header from "@/components/shared/Header";
import Footer from "@/components/shared/Footer";
import UseScrollToTop from "@/hooks/useScrollToTop";

const inter: NextFont = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
    colorScheme: 'light dark',
}

export default function RootLayout({children}: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <div className={"bg-secondary-light dark:bg-primary-dark transition duration-300"}>
            <Header/>
            {children}
            <Footer/>

            <UseScrollToTop/>
        </div>
        </body>
        </html>
    )
}